sudo: false
language: node_js
node_js:
  # LTS
  - "6"
  - "8"
  - "10"
  - "node"
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm test
  - npm run lint
  - if [ $TRAVIS_NODE_VERSION -gt 6 ]; then npm run docs:build; fi
after_success:
  - npm run report-coverage
